#!/bin/sh
# re-actvate wifi access-point when lost the link.
# need sudo without password

WIFACE=wlan0

iwconfig $WIFACE 2>/dev/null | grep 'Access Point: [A-F0-9][A-F0-9]:[A-F0-9][A-F0-9]:[A-F0-9][A-F0-9]:[A-F0-9][A-F0-9]:[A-F0-9][A-F0-9]:[A-F0-9][A-F0-9]' 2>&1 >/dev/null
ASSOCIATED=$?
#shoud be 0 for an association
if [ $ASSOCIATED -ne 0 ]
then
 echo "lost wifi link, re-activating"
 sudo iwconfig $WIFACE ap any >/dev/null 2>&1
else
 echo Wifi Link OK
fi
