#!/bin/sh
# probe for nall (see http://brouits.free.fr/nall)
# tell the global number of alive machines
# need: fping
#
HOSTNAMES=example1.com example2.org example3.net example4.info
echo `fping -a $HOSTNAMES | wc -l` alive machines
